spring:
  application:
    name:
      web3j
  datasource:
    url: jdbc:mysql://localhost/web3?serverTimezone=UTC
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

#  sql:
#    init:
#      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  batch:
    job:
      enabled: false