#1 DB ??? ?? ?? ?? ?? ???? ?

spring:
  application:
    name:
      BatchWeb3j

  datasource:
    main:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbcUrl: jdbc:mariadb://localhost:3307/meta?serverTimezone=UTC
      username: turtlecoin
      password: turtlecoin
    meta:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbcUrl: jdbc:mariadb://localhost:3307/kkobukzip?serverTimezone=UTC
      username: turtlecoin
      password: turtlecoin


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  batch:
    job:
      enabled: false