#1 DB ??? ?? ?? ?? ?? ???? ?

spring:
  application:
    name:
      BatchWeb3j
  main:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3307/kkobukzip?serverTimezone=UTC
      username: turtlecoin
      password: turtlecoin
  meta:
    datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3307/meta?serverTimezone=UTC
      username: turtlecoin
      password: turtlecoin


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  batch:
    job:
      enabled: false